export const GET_STATIONS = 'GET_STATIONS';
export const GET_SONG_LIST_FOR_STATION = 'GET_SONG_LIST_FOR_STATION';
export const GET_CURRENT_STREAM_STATE = 'GET_CURRENT_STREAM_STATE';
export const SET_ACTIVE_STATION = 'SET_ACTIVE_STATION';
export const SET_SECONDARY_STATION = 'SET_SECONDARY_STATION';